### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by sndpl** [fr3nd/msx-vi#2]
Hi, what sdcc version do you use to compile msx-vi? When I try it on my macbook with v3.7.0 I get lots of errors/warnings.

19:30:42 [:~/msx-vi] master ± make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../utils/Hex2bin-1.0.12
gcc -O2 -Wall -o hex2bin hex2bin.c
gcc -O2 -Wall -o mot2bin mot2bin.c
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C include
sdasz80 -o crt0msx_msxdos.s
sdasz80 -o crt0msx_msxdos_advanced.s
sdasz80 -o dos2.s
sdasz80 -o getchar.s
sdasz80 -o heap.s
sdasz80 -o iolib.s
sdasz80 -o ioport.s
sdasz80 -o keyboard.s
sdasz80 -o putchar.s
sdasz80 -o vdp.s
sdcc -mz80 -c -o conio.rel conio.c
sdcc -mz80 -c -o mem.rel mem.c
sdcc --code-loc 0x0178 --data-loc 0 --disable-warning 196 -mz80 --no-std-crt0 -Iinclude include/crt0msx_msxdos_advanced.rel include/heap.rel include/iolib.rel vi.c
vi.c:269: error 98: conflict with previous declaration of 'getchar' for attribute 'type' at /usr/local/bin/../share/sdcc/include/stdio.h:85
from type 'int function ( ) fixed'
  to type 'unsigned-char function ( ) fixed'
vi.c:283: error 98: conflict with previous declaration of 'putchar' for attribute 'type' at /usr/local/bin/../share/sdcc/include/stdio.h:86
from type 'int function ( int fixed) fixed'
  to type 'void function ( unsigned-char fixed) fixed'
vi.c:1318: warning 94: comparison is always false due to limited range of data type
vi.c:1320: warning 94: comparison is always false due to limited range of data type
vi.c:1327: warning 94: comparison is always false due to limited range of data type
make[1]: *** [vi.ihx] Error 1
make: *** [all] Error 2

When I fix the putchar and getchar with int instead of char I get even more errors/warnings:

19:33:44 [:~/msx-vi] master* ± make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../utils/Hex2bin-1.0.12
make[2]: Nothing to be done for 'all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C include
make[2]: Nothing to be done for 'all'.
sdcc --code-loc 0x0178 --data-loc 0 --disable-warning 196 -mz80 --no-std-crt0 -Iinclude include/crt0msx_msxdos_advanced.rel include/heap.rel include/iolib.rel vi.c
vi.c:1318: warning 94: comparison is always false due to limited range of data type
vi.c:1320: warning 94: comparison is always false due to limited range of data type
vi.c:1327: warning 94: comparison is always false due to limited range of data type
vi.c:1308: warning 94: comparison is always true resp. false due to limited range of data type
vi.c:1308: warning 94: comparison is always true resp. false due to limited range of data type
vi.c:1308: warning 94: comparison is always true resp. false due to limited range of data type
vi.c:1319: warning 126: unreachable code
vi.c:1319: warning 126: unreachable code
vi.c:1319: warning 126: unreachable code
vi.c:1319: warning 126: unreachable code
vi.c:1319: warning 126: unreachable code
vi.c:1319: warning 126: unreachable code
vi.c:1321: warning 126: unreachable code
vi.c:1321: warning 126: unreachable code
vi.c:1321: warning 126: unreachable code
vi.c:1321: warning 126: unreachable code
vi.c:1321: warning 126: unreachable code
vi.c:1321: warning 126: unreachable code
vi.c:1321: warning 126: unreachable code
vi.c:1321: warning 126: unreachable code
vi.c:1321: warning 126: unreachable code
vi.c:1321: warning 126: unreachable code
vi.c:1321: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1322: warning 126: unreachable code
vi.c:1308: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
vi.c:1308: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
vi.c:1308: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
vi.c:1313: warning 126: unreachable code
vi.c:1314: warning 126: unreachable code
vi.c:1326: warning 126: unreachable code
vi.c:1327: warning 126: unreachable code
vi.c:1385: warning 158: overflow in implicit constant conversion
vi.c:1388: warning 158: overflow in implicit constant conversion
vi.c:1419: warning 158: overflow in implicit constant conversion
vi.c:1434: warning 158: overflow in implicit constant conversion
vi.c:1471: warning 158: overflow in implicit constant conversion
vi.c:1511: warning 158: overflow in implicit constant conversion
vi.c:1607: warning 94: comparison is always true resp. false due to limited range of data type
vi.c:1607: warning 110: conditional flow changed by optimizer: so said EVELYN the modified DOG
used unbound variable in replacement

?ASlink-Warning-Undefined Global '__sdcc_heap_init' referenced by module ''
make[1]: *** [vi.ihx] Error 1
rm vi.ihx
make: *** [all] Error 2

First time I compile something with sdcc, only used msx-c before :)

**Comment by fr3nd** [comment]
I used sdcc 3.5.0 to compile. I tried to compile it with 3.7.0 and unfortunately it didn't work... they introduced several incompatible changes and it would be necessary to change the code a lot to make it work.

**Comment by fr3nd** [comment]
BTW, I've added a compile requirements section in the README with this information :)
